### ISSUE TITLE
Use pystan.stanc

### ISSUE THREAD

**Issue by ahartikainen** [Arvinds-ds/stanmagic#1]
If installed, it could use pystan.stanc function?

I don't always have CmdStan installed even if I have pystan.

**Comment by Arvinds-ds** [comment]
I use the stanc compiler for a couple of reasons. The conda install of pystan is 2.14 so I assumed it is using an older stanc compiler,  but I wanted cmdstan 2.16. I couldnt find compiler option of --allow_undefined in pystanc. Anyway I will include pystan option in 2 ways shortly..

a) If no stanc compiler is found in path
b) you specify --stanc pystan in %%stan magic

**Comment by ahartikainen** [comment]
Thanks. Sounds great.

There is a 2.15 in conda-forge https://anaconda.org/conda-forge/pystan/files

    conda install -c conda-forge pystan

But the latest release is 2.16 (this should come with pip). https://github.com/stan-dev/pystan/releases

I wil try to see if we can update the conda-forge package.

**Comment by Arvinds-ds** [comment]
Have revamped the code. It now supports pystan.stanc.  Kindly check the revised README and let me know of issues
