### ISSUE TITLE
Set variable option

### ISSUE THREAD

**Issue by ahartikainen** [Arvinds-ds/stanmagic#2]
If possible, there should be an option to put cell contents to variable.

e.g. `-v`

    %%stan -v model_code
    ....

Does this work? `setattr(model_code, cell)`

**Comment by Arvinds-ds** [comment]
Thanks.The model code is already stored in _stan_vars['stan_code']. Is there a need to specify a new object again?

**Comment by ahartikainen** [comment]
My idea was that it would be more explicit.

**Comment by Arvinds-ds** [comment]
Thanks for feedback. I am refactoring some code including stan pygments lexer to have a pretty HTML output. I will include your other requests too..

**Comment by Arvinds-ds** [comment]
I have added support for -v . But it returns an object rather than a string. You can access model_code from the object name you can specify. Pls take a look at revised README and let me know of issues
